# pyproject.toml
[build-system]
requires = [
    "setuptools>=42", 
    "setuptools_scm[toml]>=3.4",
    "setuptools_scm_git_archive",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "xrft/_version.py"
