# pyproject.toml
[build-system]
requires = [
    "setuptools>=45", 
    "setuptools_scm[toml]>=6.0",
    "setuptools_scm_git_archive",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "xrft/_version.py"
write_to_template = "__version__ = '{version}'"

